import type { ArticleIllustration } from "./article-media";

function contextualDiagram(
  afterSection: string,
  afterParagraph: number,
  asset: string,
  height: number,
  alt: string,
  caption: string,
  sourceUrl: string,
): ArticleIllustration {
  return {
    afterSection,
    afterParagraph,
    image: {
      src: `/article-media/body/deeper-rpg/${asset}.svg`,
      alt,
      width: 1000,
      height,
      caption,
      credit: "GameVerse explanatory illustration",
      sourceUrl,
    },
  };
}

export const rpgInline: Partial<Record<string, ArticleIllustration[]>> = {
  "elden-ring-starter": [
    contextualDiagram(
      "A cave trip with three decisions on the way",
      3,
      "elden-ring-cave-decisions",
      1040,
      "An invented cave route links a known Site of Grace, entrance and junction; an investigated branch returns to the junction, while an unknown encounter stays optional.",
      "Return to the recognizable junction after checking a branch. The route is invented to explain the decision; it is not a map of a particular Elden Ring cave. A rune recovery trip can end once the runes are back.",
      "https://en.bandainamcoent.eu/elden-ring/news/elden-ring-starter-guide-tips-know-playing-the-game",
    ),
    {
      afterSection: "Start with a destination you can describe",
      afterParagraph: 1,
      image: {
        src: "/article-media/body/rpg/elden-ring-cave-route.webp",
        alt: "A Tarnished holds a torch above a descending cave path among large purple crystals in Elden Ring.",
        width: 1600,
        height: 900,
        caption: "A cave gives the trip a destination. Remember the route back before another detour uses up the healing you meant to keep for the return journey.",
        credit: "FromSoftware / Bandai Namco Entertainment, via Steam",
        sourceUrl: "https://store.steampowered.com/app/1245620/",
      },
    },
    {
      afterSection: "Spend with a purpose when you return",
      afterParagraph: 1,
      image: {
        src: "/article-media/body/rpg/elden-ring-site-of-grace.webp",
        alt: "The Tarnished and Melina sit beside a glowing Site of Grace under a starry sky in Elden Ring.",
        width: 1600,
        height: 900,
        caption: "Return to a Site of Grace with one useful observation from the trip. Decide whether the next investment should improve survivability or support equipment you already know how to use.",
        credit: "FromSoftware / Bandai Namco Entertainment, via Steam",
        sourceUrl: "https://store.steampowered.com/app/1245620/",
      },
    },
  ],
  "baldurs-gate-3-starter": [
    contextualDiagram(
      "Work through a messy turn before touching the hotbar",
      2,
      "bg3-turn-branches",
      1020,
      "A hypothetical turn branches after a shot at a 7-health archer: if it falls, address the next threat; if it survives, reassess the party's remaining actions before it acts.",
      "The 7 health and 5–10 damage are illustrative. A hit can still leave the archer alive, and the attack can miss. Keep the next character's decision open until you know what actually happened.",
      "https://blog.playstation.com/2023/09/05/how-baldurs-gate-3-adapts-its-expansive-rpg-gameplay-for-your-dualsense-controller/",
    ),
    {
      afterSection: "Read the encounter before choosing an attack",
      afterParagraph: 2,
      image: {
        src: "/article-media/body/rpg/baldurs-gate-3-read-battlefield.webp",
        alt: "Baldur's Gate 3 party members face a Spectator, with the turn order, target information, map and ability bar visible.",
        width: 1600,
        height: 900,
        caption: "Check the turn order, target details and party positions before choosing the next action. This official gallery screenshot shows an older interface, so follow the labels in your own version.",
        credit: "Larian Studios, via Steam",
        sourceUrl: "https://store.steampowered.com/app/1086940/",
      },
    },
    {
      afterSection: "Make the next enemy turn smaller",
      afterParagraph: 3,
      image: {
        src: "/article-media/body/rpg/baldurs-gate-3-area-effects.webp",
        alt: "Gale casts toward gnolls as a large fire explosion fills a stone path; the combat log mentions an ignited grease surface.",
        width: 1600,
        height: 900,
        caption: "The combat log in this official screenshot records Fire Bolt igniting a grease surface. Check companions' positions and the affected ground before creating an area effect of your own.",
        credit: "Larian Studios, via Steam",
        sourceUrl: "https://store.steampowered.com/app/1086940/",
      },
    },
  ],
  "cyberpunk-2077-starter": [
    contextualDiagram(
      "Trace a job from the street to the exit",
      4,
      "cyberpunk-gig-route",
      1010,
      "An illustrative building approach connects the street and side entrance to the objective, with a known return route and a separate fallback to cover if detection occurs.",
      "Think through the entrance, objective, cover and exit as connected decisions. This schematic illustrates the example gig; it does not represent a specific Night City building or guarantee a safe route.",
      "https://www.cyberpunk.net/en/",
    ),
    {
      afterSection: "Choose one main method and one fallback",
      afterParagraph: 1,
      image: {
        src: "/article-media/body/rpg/cyberpunk-2077-close-quarters.webp",
        alt: "V holds a pistol close to an augmented opponent's head while other armed enemies surround them inside a dim Cyberpunk 2077 room.",
        width: 1600,
        height: 900,
        caption: "Enemies already within arm's reach can leave little room for the approach you planned outside. Choose a fallback you can use when the careful entrance becomes a crowded room.",
        credit: "CD PROJEKT RED, via Steam",
        sourceUrl: "https://store.steampowered.com/app/1091500/",
      },
    },
  ],
  "black-myth-wukong-starter": [
    contextualDiagram(
      "Separate a late dodge from an early counterattack",
      1,
      "wukong-followup-window",
      1020,
      "A fictional attack timeline shows first swing, pause, second swing and recovery; attacking during the pause is an early commitment, while a short answer is tested after the sequence.",
      "The pause in this invented sequence still belongs to the attack. First watch the follow-up, then test a short response after the recovery you recognize. The spacing is explanatory, with no measured boss timings.",
      "https://www.playstation.com/en-us/games/black-myth-wukong/",
    ),
    {
      afterSection: "Attempt one: find the move that causes the damage",
      afterParagraph: 2,
      image: {
        src: "/article-media/body/rpg/black-myth-wukong-attack-sequence.webp",
        alt: "A furred opponent swings a glowing blade across a shallow pool and stone courtyard in Black Myth: Wukong.",
        width: 1600,
        height: 900,
        caption: "Follow the opponent's whole swing and where it finishes before testing a punish. A still can show the space an attack crosses, but it cannot tell you the safe timing on its own.",
        credit: "Game Science, via Steam",
        sourceUrl: "https://store.steampowered.com/app/2358720/",
      },
    },
  ],
  "monster-hunter-wilds-starter": [
    contextualDiagram(
      "Compare the same three openings in the field",
      2,
      "wilds-missed-hit",
      1030,
      "Two field-test schematics distinguish an attack ending short of the target from a target moving away before the hit; adjust useful range or opening recognition accordingly.",
      "The same miss can come from distance or a late start. Change the part you diagnosed on the next opening. These positions are illustrative and do not supply weapon ranges or attack timings.",
      "https://www.playstation.com/en-ca/games/monster-hunter-wilds/monster-hunter-wilds-starters-guide/",
    ),
    {
      afterSection: "Reach changes where you should stand",
      afterParagraph: 1,
      image: {
        src: "/article-media/body/rpg/monster-hunter-wilds-ranged-spacing.webp",
        alt: "A hunter draws a bow toward a large blue wyvern across a dark, rocky slope in Monster Hunter Wilds.",
        width: 1600,
        height: 900,
        caption: "A bow changes the distance at which the hunter can engage, while the monster still determines when that distance is safe. Test an approach, a shot and a retreat instead of judging a weapon only at a stationary target.",
        credit: "CAPCOM, via Steam",
        sourceUrl: "https://store.steampowered.com/app/2246340/",
      },
    },
    {
      afterSection: "Take one weapon through a complete hunt",
      afterParagraph: 1,
      image: {
        src: "/article-media/body/rpg/monster-hunter-wilds-meal-preparation.webp",
        alt: "A hunter and a Palico prepare a large piece of cooked meat together in Monster Hunter Wilds.",
        width: 1600,
        height: 900,
        caption: "Eat and restock before taking the weapon into a full hunt. A familiar preparation routine leaves more attention for testing the moves you practiced.",
        credit: "CAPCOM, via Steam",
        sourceUrl: "https://store.steampowered.com/app/2246340/",
      },
    },
  ],
  "hades-ii-starter": [
    contextualDiagram(
      "Test the resource loop before buying more damage",
      1,
      "hades-magick-budget",
      1040,
      "Five bars show a hypothetical Magick budget falling from 40 to 30, 20, 10 and zero after four charged uses costing 10 each, without regeneration.",
      "Hypothetical arithmetic, not an in-game cost chart: 40 Magick at 10 per use funds four uses without recovery. Read your current setup for real costs, then test the ordinary action or recovery condition that keeps a longer encounter workable.",
      "https://news.xbox.com/en-us/2026/03/26/hades-2-xbox-partner-preview/",
    ),
    {
      afterSection: "Name the action doing most of the work",
      afterParagraph: 3,
      image: {
        src: "/article-media/body/rpg/hades-ii-combat-action.webp",
        alt: "Melinoë attacks enemies beside a bright cyan and pink combat effect on a stone street in Hades II.",
        width: 1600,
        height: 900,
        caption: "Watch where the action lands and where Melinoë stands afterward. Test that space in an ordinary room before choosing boons to support a move you cannot yet land reliably.",
        credit: "Supergiant Games, via Steam",
        sourceUrl: "https://store.steampowered.com/app/1145350/",
      },
    },
    {
      afterSection: "Read a boon as a sentence about your next room",
      afterParagraph: 2,
      image: {
        src: "/article-media/body/rpg/hades-ii-boon-fit.svg",
        alt: "Three checks for a Hades II boon: identify the named action, read the trigger and resource conditions, then picture using its benefit in the next room.",
        width: 1000,
        height: 980,
        caption: "A boon for Omega Attack calls for that action, rather than every attack. Read the named action and trigger, then choose for a situation you can picture in the next room. This is a decision aid, not the game's boon menu.",
        credit: "GameVerse explanatory illustration",
        sourceUrl: "https://news.xbox.com/en-us/2026/03/26/hades-2-xbox-partner-preview/",
      },
    },
  ],
  "hollow-knight-silksong-starter": [
    contextualDiagram(
      "Build a route note that survives a week away",
      2,
      "silksong-route-note",
      1010,
      "An invented route connects a known stopping point through a tall room to a quest giver; a dashed upper exit marks a ledge that the tried movement cannot reach.",
      "Record the known connection and the observed obstacle separately. The upper route remains a question until you can test it again. This is an invented note diagram, not a map of Pharloom or an upgrade requirement.",
      "https://hollowknightsilksong.com/",
    ),
    {
      afterSection: "Learn Hornet's landing position",
      afterParagraph: 2,
      image: {
        src: "/article-media/body/rpg/silksong-platform-landing.webp",
        alt: "Hornet is airborne between small moss-covered platforms above water and creatures in Hollow Knight: Silksong.",
        width: 1600,
        height: 900,
        caption: "The gap, the small platform and the creatures below make the landing part of the decision. Judge the full movement path in the room you are in, rather than repeating the same action on every stretch of floor.",
        credit: "Team Cherry, via Steam",
        sourceUrl: "https://store.steampowered.com/app/1030300/",
      },
    },
  ],
  "stardew-valley-starter": [
    contextualDiagram(
      "Plan a watering-can upgrade across three mornings",
      4,
      "stardew-watering-upgrade",
      1050,
      "A conditional three-day plan waters and hands in the can on Spring 10, relies on rain for outdoor crops on Spring 11, then collects the upgraded can and waters on Spring 12.",
      "This example requires the stated rain forecast and access to Clint for drop-off and collection. Water before handing in the can; rain covers the outdoor plot during the two-night upgrade. Check shop closures and indoor crops separately.",
      "https://wiki.stardewvalley.net/Watering_Cans",
    ),
    {
      afterSection: "Treat seeds as a commitment to future mornings",
      afterParagraph: 3,
      image: {
        src: "/article-media/body/rpg/stardew-valley-small-plot.webp",
        alt: "Two farmers stand among separated crop plots, a well, beehives and open walking paths beside a Stardew Valley farmhouse.",
        width: 1600,
        height: 900,
        caption: "Separate plots and open routes make it easier to reach crops and storage. This developed farm is a layout example, rather than a first-day shopping list or a target for your first spring.",
        credit: "ConcernedApe, via Steam",
        sourceUrl: "https://store.steampowered.com/app/413150/",
      },
    },
    {
      afterSection: "Check the calendar before buying late-season seeds",
      afterParagraph: 1,
      image: {
        src: "/article-media/body/rpg/stardew-valley-season-timing.svg",
        alt: "A parsnip planted on Spring 22 can be harvested on Spring 26 after four growth nights; one planted on Spring 25 would need Summer 1, when the outdoor spring crop withers.",
        width: 1000,
        height: 900,
        caption: "Worked example for outdoor parsnips: four growth nights, watered every day, without growth bonuses. Spring 22 leaves a harvest on Spring 26; Spring 25 runs into the season change. Multi-season crops need a separate check.",
        credit: "GameVerse explanatory illustration",
        sourceUrl: "https://wiki.stardewvalley.net/Crops",
      },
    },
  ],
};
