import type { Article } from "@/features/articles/domain/article";
import { competitiveArticles } from "./editorial/competitive-articles";
import { featureArticles } from "./editorial/feature-articles";
import { gameOverviews } from "./editorial/game-overviews";
import { rpgGames, rpgArticles } from "./editorial/expansion-rpg";
import { socialGames, socialArticles } from "./editorial/expansion-social";
import { estimateReadingMinutes } from "@/features/articles/lib/reading-time";
import type { Game } from "@/features/games/domain/game";

export const seedGames: Game[] = [
  {
    id: "gta-vi",
    slug: "gta-vi",
    title: "Grand Theft Auto VI",
    deck: gameOverviews["gta-vi"].deck,
    overview: gameOverviews["gta-vi"].body,
    genre: "Open world",
    developer: "Rockstar Games",
    publisher: "Rockstar Games",
    releaseDate: "2026-11-19",
    status: "upcoming",
    platforms: ["PS5", "Xbox Series X|S"],
    score: 96,
    heat: 100,
    accent: "#FF5A36",
    heroVariant: "sunset",
  },
  {
    id: "fortnite",
    slug: "fortnite",
    title: "Fortnite",
    deck: gameOverviews["fortnite"].deck,
    overview: gameOverviews["fortnite"].body,
    genre: "Battle royale",
    developer: "Epic Games",
    publisher: "Epic Games",
    releaseDate: null,
    status: "live",
    platforms: ["PC", "PlayStation", "Xbox", "Switch", "Mobile"],
    score: 91,
    heat: 97,
    accent: "#70E1F5",
    heroVariant: "storm",
  },
  {
    id: "minecraft",
    slug: "minecraft",
    title: "Minecraft",
    deck: gameOverviews["minecraft"].deck,
    overview: gameOverviews["minecraft"].body,
    genre: "Sandbox",
    developer: "Mojang Studios",
    publisher: "Xbox Game Studios",
    releaseDate: null,
    status: "live",
    platforms: ["PC", "PlayStation", "Xbox", "Switch", "Mobile"],
    score: 95,
    heat: 94,
    accent: "#D7FF58",
    heroVariant: "blocks",
  },
  {
    id: "valorant",
    slug: "valorant",
    title: "VALORANT",
    deck: gameOverviews["valorant"].deck,
    overview: gameOverviews["valorant"].body,
    genre: "Tactical shooter",
    developer: "Riot Games",
    publisher: "Riot Games",
    releaseDate: null,
    status: "live",
    platforms: ["PC", "PS5", "Xbox Series X|S"],
    score: 90,
    heat: 92,
    accent: "#FF6B6B",
    heroVariant: "signal",
  },
  {
    id: "counter-strike-2",
    slug: "counter-strike-2",
    title: "Counter-Strike 2",
    deck: gameOverviews["counter-strike-2"].deck,
    overview: gameOverviews["counter-strike-2"].body,
    genre: "Tactical shooter",
    developer: "Valve",
    publisher: "Valve",
    releaseDate: null,
    status: "live",
    platforms: ["PC"],
    score: 92,
    heat: 91,
    accent: "#F4B860",
    heroVariant: "smoke",
  },
  {
    id: "league-of-legends",
    slug: "league-of-legends",
    title: "League of Legends",
    deck: gameOverviews["league-of-legends"].deck,
    overview: gameOverviews["league-of-legends"].body,
    genre: "MOBA",
    developer: "Riot Games",
    publisher: "Riot Games",
    releaseDate: null,
    status: "live",
    platforms: ["PC"],
    score: 93,
    heat: 90,
    accent: "#C9A34E",
    heroVariant: "rift",
  },
  {
    id: "roblox",
    slug: "roblox",
    title: "Roblox",
    deck: gameOverviews["roblox"].deck,
    overview: gameOverviews["roblox"].body,
    genre: "Platform",
    developer: "Roblox Corporation",
    publisher: "Roblox Corporation",
    releaseDate: null,
    status: "live",
    platforms: ["PC", "PlayStation", "Xbox", "Mobile"],
    score: 86,
    heat: 89,
    accent: "#E7E4DD",
    heroVariant: "grid",
  },
  {
    id: "genshin-impact",
    slug: "genshin-impact",
    title: "Genshin Impact",
    deck: gameOverviews["genshin-impact"].deck,
    overview: gameOverviews["genshin-impact"].body,
    genre: "Action RPG",
    developer: "HoYoverse",
    publisher: "HoYoverse",
    releaseDate: null,
    status: "live",
    platforms: ["PC", "PlayStation", "Xbox", "Mobile"],
    score: 89,
    heat: 87,
    accent: "#A8C5FF",
    heroVariant: "sky",
  },
  ...rpgGames,
  ...socialGames,
];

export const seedArticles: Article[] = [...featureArticles, ...competitiveArticles, ...rpgArticles, ...socialArticles]
  .map((article) => ({ ...article, readMinutes: estimateReadingMinutes(article.body) }))
  .sort((a, b) => b.publishedAt.localeCompare(a.publishedAt));
