import type { GameArtwork } from "./game-artwork";

export const expansionArtwork: Record<
  string,
  GameArtwork & { width: number; height: number; caption: string }
> = {
  "elden-ring": {
    src: "/game-media/expansion/elden-ring-cover.webp",
    alt: "An armored rider overlooks a ruined landscape beneath the glowing branches of the Erdtree in Elden Ring.",
    width: 1600,
    height: 900,
    caption: "The Erdtree is a landmark across the Lands Between. An open route can be worth exploring before another attempt at a boss.",
    credit: "FromSoftware / Bandai Namco Entertainment, via Steam",
    sourceUrl: "https://store.steampowered.com/app/1245620/",
  },
  "baldurs-gate-3": {
    src: "/game-media/expansion/baldurs-gate-3-cover.webp",
    alt: "Four adventurers stand on a grassy ridge overlooking mountains and a valley in Baldur's Gate 3.",
    width: 1600,
    height: 900,
    caption: "A party has several ways to approach the same problem. Leave room for dialogue and exploration between fights.",
    credit: "Larian Studios, via Steam",
    sourceUrl: "https://store.steampowered.com/app/1086940/",
  },
  "cyberpunk-2077": {
    src: "/game-media/expansion/cyberpunk-2077-cover.webp",
    alt: "A Night City street beneath elevated roads, with neon signs and pedestrians in Cyberpunk 2077.",
    width: 1600,
    height: 900,
    caption: "Night City's side streets give you reasons to slow down. Choose a combat approach that leaves time to explore between jobs.",
    credit: "CD PROJEKT RED, via Steam",
    sourceUrl: "https://store.steampowered.com/app/1091500/",
  },
  "black-myth-wukong": {
    src: "/game-media/expansion/black-myth-wukong-cover.webp",
    alt: "The staff-wielding protagonist faces a fiery opponent in a shadowed woodland in Black Myth: Wukong.",
    width: 1600,
    height: 900,
    caption: "Read an opponent's wind-up before committing to a long staff combo. A short opening still has room for a measured response.",
    credit: "Game Science, via Steam",
    sourceUrl: "https://store.steampowered.com/app/2358720/",
  },
  "monster-hunter-wilds": {
    src: "/game-media/expansion/monster-hunter-wilds-cover.webp",
    alt: "A hunter confronts a large orange-furred monster in a sunlit grassland in Monster Hunter Wilds.",
    width: 1600,
    height: 900,
    caption: "Watch a monster's recovery, then decide whether there is time to attack, heal or move. Preparation continues after the hunt begins.",
    credit: "CAPCOM, via Steam",
    sourceUrl: "https://store.steampowered.com/app/2246340/",
  },
  "hades-ii": {
    src: "/game-media/expansion/hades-ii-cover.webp",
    alt: "Melinoë fights enemies with bright spell effects in a purple-lit grove in Hades II.",
    width: 1600,
    height: 900,
    caption: "A crowded encounter is a good reason to leave a clear route out of the next attack. Try a new weapon with movement in mind.",
    credit: "Supergiant Games, via Steam",
    sourceUrl: "https://store.steampowered.com/app/1145350/",
  },
  "hollow-knight-silksong": {
    src: "/game-media/expansion/hollow-knight-silksong-cover.webp",
    alt: "Hornet stands beside a carved stone sphere amid green foliage in Hollow Knight: Silksong.",
    width: 1600,
    height: 900,
    caption: "Hornet's route through Pharloom moves between exploration, platforming and encounters. Pay attention to the path as well as the next opponent.",
    credit: "Team Cherry, via Steam",
    sourceUrl: "https://store.steampowered.com/app/1030300/",
  },
  "stardew-valley": {
    src: "/game-media/expansion/stardew-valley-cover.webp",
    alt: "A Stardew Valley farm with a farmhouse, barn, crop rows and fenced animal pens.",
    width: 1600,
    height: 900,
    caption: "Crops, animals and buildings share the same farm. Leave space for paths before adding the next project.",
    credit: "ConcernedApe, via Steam",
    sourceUrl: "https://store.steampowered.com/app/413150/",
  },
  "helldivers-2": {
    src: "/game-media/expansion/helldivers-2-cover.webp",
    alt: "A helmeted Helldiver aims a rifle through a smoky battlefield with insect-like enemies behind them.",
    width: 1600,
    height: 900,
    caption: "Publisher screenshot captured on PS5. Keeping space between squadmates gives each player a clearer firing lane.",
    credit: "Arrowhead Game Studios / PlayStation, via Steam",
    sourceUrl: "https://store.steampowered.com/app/553850/",
  },
  palworld: {
    src: "/game-media/expansion/palworld-cover.webp",
    alt: "Riders on flying Pals cross a rocky valley with distant towers in Palworld.",
    width: 1600,
    height: 900,
    caption: "Flying opens up the view, while a working base makes the return trip easier. This is an official publisher gallery scene.",
    credit: "Pocketpair, via Steam",
    sourceUrl: "https://store.steampowered.com/app/1623730/",
  },
  "sea-of-thieves": {
    src: "/game-media/expansion/sea-of-thieves-cover.webp",
    alt: "A fleet of pirate ships with colorful sails crosses blue water in Sea of Thieves.",
    width: 1600,
    height: 901,
    caption: "A clear job on deck helps a crew react when another sail appears. This official gallery scene shows several ships together.",
    credit: "Rare / Xbox Game Studios, via Steam",
    sourceUrl: "https://store.steampowered.com/app/1172620/",
  },
  "no-mans-sky": {
    src: "/game-media/expansion/no-mans-sky-cover.webp",
    alt: "An explorer stands beside a red spacecraft on a grassy planet with tall alien plants in No Man's Sky.",
    width: 1600,
    height: 900,
    caption: "A landing can give the session a simple plan: check supplies, choose one place to explore and remember the route back.",
    credit: "Hello Games, via Steam",
    sourceUrl: "https://store.steampowered.com/app/275850/",
  },
  "forza-horizon-5": {
    src: "/game-media/expansion/forza-horizon-5-cover.webp",
    alt: "An off-road racing truck jumps along a dusty coastal route with other cars in Forza Horizon 5.",
    width: 1600,
    height: 900,
    caption: "Begin with a car that suits the surface, then compare clean runs along the same route. This official scene shows off-road racing near the coast.",
    credit: "Playground Games / Xbox Game Studios, via Steam",
    sourceUrl: "https://store.steampowered.com/app/1551360/",
  },
  "civilization-vii": {
    src: "/game-media/expansion/civilization-vii-cover.webp",
    alt: "A coastal city with a circular arena, dense buildings and rocky hills in Civilization VII.",
    width: 1600,
    height: 900,
    caption: "Cities grow into the land around them. Choose the next settlement's job before asking it to solve every shortage at once.",
    credit: "Firaxis Games / 2K, via Steam",
    sourceUrl: "https://store.steampowered.com/app/1295660/",
  },
  "street-fighter-6": {
    src: "/game-media/expansion/street-fighter-6-cover.webp",
    alt: "Ryu and Chun-Li exchange attacks beside a Japanese gate and flowering trees in Street Fighter 6.",
    width: 1600,
    height: 900,
    caption: "Ryu and Chun-Li in an official match screenshot. Spacing leaves time to see an approach before choosing a response.",
    credit: "CAPCOM, via Steam",
    sourceUrl: "https://store.steampowered.com/app/1364780/",
  },
  "ea-sports-fc-26": {
    src: "/game-media/expansion/ea-sports-fc-26-cover.webp",
    alt: "A Bayern Munich player contests the ball with two Manchester City players in an EA SPORTS FC 26 match scene.",
    width: 1600,
    height: 900,
    caption: "An official in-game match still. Stay close enough to contest the next pass while protecting the route toward goal.",
    credit: "EA SPORTS / Electronic Arts, via Steam",
    sourceUrl: "https://store.steampowered.com/app/3405690/",
  },
};
